module.exports = {
  root: true,
  env: {
    "es6": true
  },
  extends: [
    "eslint:recommended"
  ],
  parserOptions: {
    ecmaVersion: 2020,
    sourceType:  'module'
  },
  rules: {
    "prefer-template": "error",
    "prefer-destructuring": "error",
    "prefer-object-spread": "error",
    "quotes": ["error", "single"],
    "quote-props": ["error", "consistent-as-needed"],
    "no-extra-parens": "error",
    "no-template-curly-in-string": "error",
    "array-callback-return": "error",
    "consistent-return": "error",
    "curly": "error",
    "default-param-last": "error",
    "default-case": "error",
    "dot-location": ["error", "property"],
    "dot-notation": "error",
    "eqeqeq": "error",
    "grouped-accessor-pairs": "error",
    "no-alert": "error",
    "no-caller": "error",
    "no-constructor-return": "error",
    "no-div-regex": "error",
    "no-else-return": ["error", {allowElseIf: false}],
    "no-empty-function": "error",
    "no-eq-null": "error",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-extra-label": "error",
    "no-floating-decimal": "error",
    "no-implicit-coercion": "error",
    "no-implied-eval": "error",
    "no-invalid-this": "error",
    "no-iterator": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-loop-func": "error",
    "no-magic-numbers": ["error", { 
      "enforceConst": true, 
      "detectObjects": true,
      "ignore": [0, 1]
    }], // TODO: check: Mayby overkill? but butiful 
    "no-multi-spaces": ["error", { exceptions: { Property: true, VariableDeclarator: true, ImportDeclaration: true}}],
    "no-multi-str": "error",
    "no-new": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-octal-escape": "error",
    "no-param-reassign": "error",
    "no-proto": "error",
    "no-return-assign": "error",
    "no-return-await": "error",
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-throw-literal": "error",
    "no-unmodified-loop-condition": "error",
    "no-unused-expressions": "error",
    "no-useless-call": "error",
    "no-useless-concat": "error",
    "no-useless-return": "error",
    "no-void": "error",
    "prefer-named-capture-group": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-regex-literals": "error",
    "radix": "error",  
    "require-await": "error", // TODO: unnessesary? bad design?
    "require-unicode-regexp": "error",
    "vars-on-top": "error",
    "wrap-iife": ["error", "inside"],
    "yoda": "error",
    "no-label-var": "error",
    "no-shadow": ["error", { "builtinGlobals": true, "hoist": "all" }],
    "no-undef-init": "error",
    "no-undefined": "error",
    "no-use-before-define": "error",
    "callback-return": "error",
    "global-require": "error",
    "handle-callback-err": "error",
    "no-buffer-constructor": "error",
    "no-new-require": "error",
    "no-path-concat": "error",
    "no-process-env": "error",
    "no-sync": "error",
    "array-bracket-newline": ["warn", { "minItems": 3 }], // TODO: change to min items xxx
    "array-bracket-spacing": ["warn", "always", { 
      "singleValue": false, 
      "arraysInArrays": false, 
      "objectsInArrays": false 
    }],
    "array-element-newline": ["warn", { "minItems": 3 }], // TODO: change to min items xxx,
    "block-spacing": ["error", "always"],
    "brace-style": "error",
    "camelcase": "error",
    "comma-dangle": ["error", "never"],
    "comma-spacing": ["error", { "before": false, "after": true }],
    "comma-style": ["error", "last"],
    "computed-property-spacing": ["error", "never", { "enforceForClassMembers": true }],
    "consistent-this": "error",
    "eol-last": "error",
    "func-call-spacing": "error",
    "func-name-matching": "error",
    "func-names": ["error", "as-needed"],
    "func-style": ["error", "declaration", { "allowArrowFunctions": true }],
    "function-paren-newline": ["error", "multiline-arguments"],
    "id-length": ["error", { "min": 2, "max": 25 }],
    "implicit-arrow-linebreak": ["error", "beside"],
    "indent": ["error", 2, {
      "SwitchCase": 1,
      "VariableDeclarator": "first",
      "outerIIFEBody": 1,
      "MemberExpression": 1,
      "FunctionDeclaration": { "parameters": 2, "body": 1 },
      "FunctionExpression": { "parameters": 2, "body": 1 },
      "CallExpression": { "arguments": 1 },
      "ArrayExpression": 1,
      "ObjectExpression": 1,
      "ImportDeclaration": 1,
      "flatTernaryExpressions": false,
      "ignoreComments": false,
      "ignoredNodes": ["TemplateLiteral *", "JSXElement", "JSXElement > *", "JSXAttribute", "JSXIdentifier", "JSXNamespacedName", "JSXMemberExpression", "JSXSpreadAttribute", "JSXExpressionContainer", "JSXOpeningElement", "JSXClosingElement", "JSXFragment", "JSXOpeningFragment", "JSXClosingFragment", "JSXText", "JSXEmptyExpression", "JSXSpreadChild"],
      "offsetTernaryExpressions": true
    }],
    "jsx-quotes": ["error", "prefer-double"],
    "key-spacing": ["error", { "beforeColon": false, "afterColon": true }],
    "keyword-spacing": "error",
    "linebreak-style": "error",
    "lines-between-class-members": ["error", "always", { "exceptAfterSingleLine": true }],
    "max-depth": "error",
    "max-len": ["warn", 90, "ignoreComments": true],
    "max-nested-callbacks": ["error", 3],
    "max-params": "error",
    "max-statements-per-line": "error",
    "new-cap": "error",
    "new-parens": ["error", "always"],
    "newline-per-chained-call": "error",
    "no-array-constructor": "error",
    "no-bitwise": "error", 
    "no-lonely-if": "error",
    "no-multi-assign": "error",
    "no-multiple-empty-lines": "error",
    "no-negated-condition": "error",
    "no-nested-ternary": "error",
    "no-new-object": "error",
    "no-plusplus": ["error", { "allowForLoopAfterthoughts": true }],
    "no-trailing-spaces": "error",
    "no-underscore-dangle": "error",
    "no-unneeded-ternary": "error",
    "no-whitespace-before-property": "error",
    "nonblock-statement-body-position": ["error", "below"],
    'object-curly-spacing': ['error', 'always'],
    'object-curly-newline': ['error', {
      ObjectExpression: { minProperties: 4, multiline: true, consistent: true },
      ObjectPattern: { minProperties: 4, multiline: true, consistent: true },
      ImportDeclaration: { minProperties: 4, multiline: true, consistent: true },
      ExportDeclaration: { minProperties: 4, multiline: true, consistent: true },
    }],
    'object-property-newline': 'error',
    "one-var": ["error", "never"],
    "one-var-declaration-per-line": ["error", "always"],
    "operator-assignment": ["error", "always"],
    "operator-linebreak": ["error", "before"],
    "padding-line-between-statements": [
      "error", // TODO: NICE
      { blankLine: "always", prev: "directive", next: "*" }, 
      { blankLine: "any", prev: "directive", next: "directive" },
      { blankLine: "always", prev: ["const", "let", "var"], next: "*"},
      { blankLine: "any",    prev: ["const", "let", "var"], next: ["const", "let", "var"]},
      { blankLine: "always", prev: "*", next: "return" },
      { blankLine: "always", prev: ["cjs-export", "cjs-import", "import", "export"], next: "*"},
      { blankLine: "any",    prev: ["cjs-export", "cjs-import", "import", "export"], next: ["cjs-export", "cjs-import", "import", "export"]},
      { blankLine: "always", prev: "*", next: "multiline-block-like" }
    ],
    "prefer-exponentiation-operator": "error",
    "prefer-object-spread": "error",
    "semi": ["error", "always", { "omitLastInOneLineBlock": true}],
    "semi-spacing": ["error", {"before": false, "after": true}],
    "semi-style": ["error", "last"],
    "sort-vars": "error",
    "space-before-blocks": "error",
    "space-before-function-paren": ["error", "never"],
    "space-in-parens": "error",
    "space-infix-ops": "error",
    "space-unary-ops": "error",
    "spaced-comment": "error",
    "switch-colon-spacing": "error",
    "template-tag-spacing": "error",
    "wrap-regex": "error",
    "arrow-body-style": "error",
    "arrow-parens": ["error", "as-needed"],
    "arrow-spacing": "error",
    "no-confusing-arrow": "error",
    "no-duplicate-imports": ["error", { "includeExports": true }],
    "no-useless-computed-key": "error",
    "no-useless-constructor": "error",
    "no-useless-rename": "error",
    "no-var": "error",
    "no-return-await": "error",
    "object-shorthand": ["error", "always", { "avoidQuotes": true }],
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "prefer-destructuring": "error",
    "prefer-numeric-literals": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "rest-spread-spacing": ["error", "never"],
    "symbol-description": "error",
    "template-curly-spacing": "error"
  }
};
